FROM rust:1.76-slim AS builder

RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app
COPY . .

WORKDIR /usr/src/app/agent
RUN cargo build --release --target x86_64-unknown-linux-gnu

FROM scratch
COPY --from=builder /usr/src/app/target/x86_64-unknown-linux-gnu/release/activity-monitor-agent /
